import { describe, expect, it } from 'vitest'

import { getYouTubeClient } from '~/lib/youtube/client'

import { youtubeProvider } from '../youtube'

const YOUTUBE_URL = 'https://www.youtube.com/watch?v=9qIHqX6rdiw'

describe('youtubeProvider.fetchMetadata', () => {
	it('fetches live metadata using the provided client', async () => {
		const youtubeClient = await getYouTubeClient({
			proxy: 'http://127.0.0.1:7890',
		})

		const metadata = await youtubeProvider.fetchMetadata(YOUTUBE_URL, {
			youtubeClient,
		})

		expect(metadata?.raw).toMatchInlineSnapshot(`
			VideoInfo {
			  "annotations": [
			    PlayerAnnotationsExpanded {
			      "allow_swipe_dismiss": true,
			      "annotation_id": "58360423-0000-2268-833e-94eb2c08d038",
			      "featured_channel": {
			        "channel_name": "CGTN",
			        "end_time_ms": "79000",
			        "endpoint": NavigationEndpoint {
			          "command": BrowseEndpoint {
			            "type": "BrowseEndpoint",
			          },
			          "commands": undefined,
			          "dialog": undefined,
			          "metadata": {
			            "api_url": "browse",
			            "page_type": "WEB_PAGE_TYPE_CHANNEL",
			            "url": "/channel/UCgrNz-aDmcr2uuto8_DL2jg",
			          },
			          "modal": undefined,
			          "name": "browseEndpoint",
			          "next_endpoint": undefined,
			          "open_popup": undefined,
			          "payload": {
			            "browseId": "UCgrNz-aDmcr2uuto8_DL2jg",
			          },
			          "type": "NavigationEndpoint",
			        },
			        "start_time_ms": "0",
			        "subscribe_button": SubscribeButton {
			          "button_text": Text {
			            "accessibility": undefined,
			            "endpoint": undefined,
			            "rtl": false,
			            "runs": [
			              TextRun {
			                "attachment": undefined,
			                "bold": false,
			                "bracket": false,
			                "dark_mode_text_color": undefined,
			                "deemphasize": false,
			                "endpoint": undefined,
			                "error_underline": false,
			                "font_face": undefined,
			                "italics": false,
			                "strikethrough": false,
			                "text": "SUBSCRIBE",
			                "text_color": undefined,
			                "underline": false,
			              },
			            ],
			            "text": "SUBSCRIBE",
			          },
			          "channel_id": "UCgrNz-aDmcr2uuto8_DL2jg",
			          "enabled": true,
			          "item_type": "FREE",
			          "notification_preference_button": null,
			          "on_subscribe_endpoints": undefined,
			          "on_unsubscribe_endpoints": undefined,
			          "service_endpoints": [
			            NavigationEndpoint {
			              "command": SubscribeEndpoint {
			                "type": "SubscribeEndpoint",
			              },
			              "commands": undefined,
			              "dialog": undefined,
			              "metadata": {
			                "api_url": "subscription/subscribe",
			                "send_post": true,
			              },
			              "modal": undefined,
			              "name": "subscribeEndpoint",
			              "next_endpoint": undefined,
			              "open_popup": undefined,
			              "payload": {
			                "channelIds": [
			                  "UCgrNz-aDmcr2uuto8_DL2jg",
			                ],
			                "params": "EgIIBBgA",
			              },
			              "type": "NavigationEndpoint",
			            },
			            NavigationEndpoint {
			              "command": SignalServiceEndpoint {
			                "actions": [
			                  OpenPopupAction {
			                    "popup": ConfirmDialog {
			                      "cancel_button": Button {
			                        "accessibility": undefined,
			                        "endpoint": NavigationEndpoint {
			                          "command": undefined,
			                          "commands": undefined,
			                          "dialog": undefined,
			                          "metadata": {},
			                          "modal": undefined,
			                          "name": undefined,
			                          "next_endpoint": undefined,
			                          "open_popup": undefined,
			                          "payload": {},
			                          "type": "NavigationEndpoint",
			                        },
			                        "icon_type": undefined,
			                        "is_disabled": false,
			                        "label": "Cancel",
			                        "size": "SIZE_DEFAULT",
			                        "style": "STYLE_TEXT",
			                        "target_id": undefined,
			                        "text": "Cancel",
			                        "tooltip": undefined,
			                        "type": "Button",
			                      },
			                      "confirm_button": Button {
			                        "accessibility": undefined,
			                        "endpoint": NavigationEndpoint {
			                          "command": UnsubscribeEndpoint {
			                            "type": "UnsubscribeEndpoint",
			                          },
			                          "commands": undefined,
			                          "dialog": undefined,
			                          "metadata": {
			                            "api_url": "subscription/unsubscribe",
			                            "send_post": true,
			                          },
			                          "modal": undefined,
			                          "name": "unsubscribeEndpoint",
			                          "next_endpoint": undefined,
			                          "open_popup": undefined,
			                          "payload": {
			                            "channelIds": [
			                              "UCgrNz-aDmcr2uuto8_DL2jg",
			                            ],
			                            "params": "CgIIBBgA",
			                          },
			                          "type": "NavigationEndpoint",
			                        },
			                        "icon_type": undefined,
			                        "is_disabled": false,
			                        "label": "Unsubscribe",
			                        "size": "SIZE_DEFAULT",
			                        "style": "STYLE_BLUE_TEXT",
			                        "target_id": undefined,
			                        "text": "Unsubscribe",
			                        "tooltip": undefined,
			                        "type": "Button",
			                      },
			                      "dialog_messages": [
			                        Text {
			                          "accessibility": undefined,
			                          "endpoint": undefined,
			                          "rtl": false,
			                          "runs": [
			                            TextRun {
			                              "attachment": undefined,
			                              "bold": false,
			                              "bracket": false,
			                              "dark_mode_text_color": undefined,
			                              "deemphasize": false,
			                              "endpoint": undefined,
			                              "error_underline": false,
			                              "font_face": undefined,
			                              "italics": false,
			                              "strikethrough": false,
			                              "text": "Unsubscribe from ",
			                              "text_color": undefined,
			                              "underline": false,
			                            },
			                            TextRun {
			                              "attachment": undefined,
			                              "bold": false,
			                              "bracket": false,
			                              "dark_mode_text_color": undefined,
			                              "deemphasize": false,
			                              "endpoint": undefined,
			                              "error_underline": false,
			                              "font_face": undefined,
			                              "italics": false,
			                              "strikethrough": false,
			                              "text": "CGTN",
			                              "text_color": undefined,
			                              "underline": false,
			                            },
			                            TextRun {
			                              "attachment": undefined,
			                              "bold": false,
			                              "bracket": false,
			                              "dark_mode_text_color": undefined,
			                              "deemphasize": false,
			                              "endpoint": undefined,
			                              "error_underline": false,
			                              "font_face": undefined,
			                              "italics": false,
			                              "strikethrough": false,
			                              "text": "?",
			                              "text_color": undefined,
			                              "underline": false,
			                            },
			                          ],
			                          "text": "Unsubscribe from CGTN?",
			                        },
			                      ],
			                      "title": Text {
			                        "accessibility": undefined,
			                        "endpoint": undefined,
			                        "rtl": false,
			                        "runs": undefined,
			                        "text": undefined,
			                      },
			                      "type": "ConfirmDialog",
			                    },
			                    "popup_type": "DIALOG",
			                    "type": "OpenPopupAction",
			                  },
			                ],
			                "signal": "CLIENT_SIGNAL",
			                "type": "SignalServiceEndpoint",
			              },
			              "commands": undefined,
			              "dialog": undefined,
			              "metadata": {
			                "api_url": undefined,
			                "send_post": true,
			              },
			              "modal": undefined,
			              "name": "signalServiceEndpoint",
			              "next_endpoint": undefined,
			              "open_popup": undefined,
			              "payload": {
			                "actions": [
			                  {
			                    "openPopupAction": {
			                      "popup": {
			                        "confirmDialogRenderer": {
			                          "cancelButton": {
			                            "buttonRenderer": {
			                              "accessibility": {
			                                "label": "Cancel",
			                              },
			                              "isDisabled": false,
			                              "size": "SIZE_DEFAULT",
			                              "style": "STYLE_TEXT",
			                              "text": {
			                                "runs": [
			                                  {
			                                    "text": "Cancel",
			                                  },
			                                ],
			                              },
			                              "trackingParams": "CAwQ8FsiEwi7lrT72Y2QAxXWVZ0JHQ0XG0U=",
			                            },
			                          },
			                          "confirmButton": {
			                            "buttonRenderer": {
			                              "accessibility": {
			                                "label": "Unsubscribe",
			                              },
			                              "isDisabled": false,
			                              "serviceEndpoint": {
			                                "clickTrackingParams": "CA0Q8FsiEwi7lrT72Y2QAxXWVZ0JHQ0XG0UyAml2ygEEQ_F6dA==",
			                                "commandMetadata": {
			                                  "webCommandMetadata": {
			                                    "apiUrl": "/youtubei/v1/subscription/unsubscribe",
			                                    "sendPost": true,
			                                  },
			                                },
			                                "unsubscribeEndpoint": {
			                                  "channelIds": [
			                                    "UCgrNz-aDmcr2uuto8_DL2jg",
			                                  ],
			                                  "params": "CgIIBBgA",
			                                },
			                              },
			                              "size": "SIZE_DEFAULT",
			                              "style": "STYLE_BLUE_TEXT",
			                              "text": {
			                                "runs": [
			                                  {
			                                    "text": "Unsubscribe",
			                                  },
			                                ],
			                              },
			                              "trackingParams": "CA0Q8FsiEwi7lrT72Y2QAxXWVZ0JHQ0XG0U=",
			                            },
			                          },
			                          "dialogMessages": [
			                            {
			                              "runs": [
			                                {
			                                  "text": "Unsubscribe from ",
			                                },
			                                {
			                                  "text": "CGTN",
			                                },
			                                {
			                                  "text": "?",
			                                },
			                              ],
			                            },
			                          ],
			                          "primaryIsCancel": false,
			                          "trackingParams": "CAsQxjgiEwi7lrT72Y2QAxXWVZ0JHQ0XG0U=",
			                        },
			                      },
			                      "popupType": "DIALOG",
			                    },
			                  },
			                ],
			                "signal": "CLIENT_SIGNAL",
			              },
			              "type": "NavigationEndpoint",
			            },
			          ],
			          "show_preferences": false,
			          "subscribe_accessibility_label": "Subscribe to CGTN.",
			          "subscribed": false,
			          "subscribed_entity_key": undefined,
			          "subscribed_text": Text {
			            "accessibility": undefined,
			            "endpoint": undefined,
			            "rtl": false,
			            "runs": [
			              TextRun {
			                "attachment": undefined,
			                "bold": false,
			                "bracket": false,
			                "dark_mode_text_color": undefined,
			                "deemphasize": false,
			                "endpoint": undefined,
			                "error_underline": false,
			                "font_face": undefined,
			                "italics": false,
			                "strikethrough": false,
			                "text": "SUBSCRIBED",
			                "text_color": undefined,
			                "underline": false,
			              },
			            ],
			            "text": "SUBSCRIBED",
			          },
			          "target_id": undefined,
			          "type": "SubscribeButton",
			          "unsubscribe_accessibility_label": "Unsubscribe from CGTN.",
			          "unsubscribe_text": Text {
			            "accessibility": undefined,
			            "endpoint": undefined,
			            "rtl": false,
			            "runs": [
			              TextRun {
			                "attachment": undefined,
			                "bold": false,
			                "bracket": false,
			                "dark_mode_text_color": undefined,
			                "deemphasize": false,
			                "endpoint": undefined,
			                "error_underline": false,
			                "font_face": undefined,
			                "italics": false,
			                "strikethrough": false,
			                "text": "UNSUBSCRIBE",
			                "text_color": undefined,
			                "underline": false,
			              },
			            ],
			            "text": "UNSUBSCRIBE",
			          },
			          "unsubscribed_text": Text {
			            "accessibility": undefined,
			            "endpoint": undefined,
			            "rtl": false,
			            "runs": [
			              TextRun {
			                "attachment": undefined,
			                "bold": false,
			                "bracket": false,
			                "dark_mode_text_color": undefined,
			                "deemphasize": false,
			                "endpoint": undefined,
			                "error_underline": false,
			                "font_face": undefined,
			                "italics": false,
			                "strikethrough": false,
			                "text": "SUBSCRIBE",
			                "text_color": undefined,
			                "underline": false,
			              },
			            ],
			            "text": "SUBSCRIBE",
			          },
			        },
			        "watermark": [
			          Thumbnail {
			            "height": 40,
			            "url": "https://i.ytimg.com/an/grNz-aDmcr2uuto8_DL2jg/featured_channel.jpg?v=638716c6",
			            "width": 40,
			          },
			        ],
			      },
			      "type": "PlayerAnnotationsExpanded",
			    },
			  ],
			  "autoplay": undefined,
			  "basic_info": {
			    "allow_ratings": true,
			    "author": "CGTN",
			    "category": "News & Politics",
			    "channel": {
			      "id": "UCgrNz-aDmcr2uuto8_DL2jg",
			      "name": "CGTN",
			      "url": "http://www.youtube.com/@cgtn",
			    },
			    "channel_id": "UCgrNz-aDmcr2uuto8_DL2jg",
			    "duration": 79,
			    "embed": {
			      "flash_secure_url": undefined,
			      "flash_url": undefined,
			      "height": 720,
			      "iframe_url": "https://www.youtube.com/embed/9qIHqX6rdiw",
			      "width": 1280,
			    },
			    "end_timestamp": null,
			    "has_ypc_metadata": false,
			    "id": "9qIHqX6rdiw",
			    "is_crawlable": true,
			    "is_disliked": undefined,
			    "is_family_safe": true,
			    "is_liked": undefined,
			    "is_live": false,
			    "is_live_content": false,
			    "is_live_dvr_enabled": false,
			    "is_low_latency_live_stream": false,
			    "is_owner_viewing": false,
			    "is_post_live_dvr": false,
			    "is_private": false,
			    "is_unlisted": false,
			    "is_upcoming": false,
			    "keywords": [
			      "CGTN",
			      "News",
			    ],
			    "like_count": undefined,
			    "live_chunk_readahead": undefined,
			    "short_description": "For  more:
			https://news.cgtn.com/news/2025-09-27/Chinese-astronauts-capture-stunning-space-movie-using-8K-cameras-1H0TDF7IFd6/p.html

			In a groundbreaking achievement, Chinese astronauts Zhai Zhigang, Wang Yaping and Ye Guangfu have filmed a visually breathtaking space movie in Earth's orbit using an 8K space camera aboard the Chinese space station. The film, based on the Shenzhou 13 mission's historic six-month stay in orbit, offers a unique perspective through astronaut Wang Yaping's eyes. It combines profound emotional depth, striking visuals and cosmic reflection, all wrapped in a rich tapestry of Chinese space aesthetics, taking viewers on an extraordinary journey beyond the stars.

			Subscribe to us on YouTube: https://goo.gl/lP12gA
			Download our APP on Apple Store (iOS): https://itunes.apple.com/us/app/cctvnews-app/id922456579?l=zh&ls=1&mt=8
			Download our APP on Google Play (Android): https://play.google.com/store/apps/details?id=com.imib.cctv",
			    "start_timestamp": null,
			    "tags": null,
			    "thumbnail": [
			      Thumbnail {
			        "height": 1080,
			        "url": "https://i.ytimg.com/vi/9qIHqX6rdiw/maxresdefault.jpg",
			        "width": 1920,
			      },
			      Thumbnail {
			        "height": 188,
			        "url": "https://i.ytimg.com/vi/9qIHqX6rdiw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrLU014HQW0oSE-ge_cqxEBk0Pfg",
			        "width": 336,
			      },
			      Thumbnail {
			        "height": 138,
			        "url": "https://i.ytimg.com/vi/9qIHqX6rdiw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDT8sr2kBpIg-eAM4f5-FmaxSHC4Q",
			        "width": 246,
			      },
			      Thumbnail {
			        "height": 110,
			        "url": "https://i.ytimg.com/vi/9qIHqX6rdiw/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBtP5aOAdXhD0SV0I3dfGj--_hoLQ",
			        "width": 196,
			      },
			      Thumbnail {
			        "height": 94,
			        "url": "https://i.ytimg.com/vi/9qIHqX6rdiw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD8t110Zfcv1gKec2cW2uyZ5dhMiw",
			        "width": 168,
			      },
			    ],
			    "title": "Chinese astronauts capture stunning space movie using 8K cameras",
			    "url_canonical": null,
			    "view_count": 52294,
			  },
			  "captions": undefined,
			  "cards": CardCollection {
			    "allow_teaser_dismiss": true,
			    "cards": [
			      Card {
			        "card_id": undefined,
			        "content": null,
			        "cue_ranges": [
			          {
			            "end_card_active_ms": "5000",
			            "icon_after_teaser_ms": "5000",
			            "start_card_active_ms": "0",
			            "teaser_duration_ms": "6000",
			          },
			        ],
			        "feature": undefined,
			        "teaser": SimpleCardTeaser {
			          "message": Text {
			            "accessibility": undefined,
			            "endpoint": undefined,
			            "rtl": false,
			            "runs": undefined,
			            "text": "View corrections",
			          },
			          "prominent": true,
			          "type": "SimpleCardTeaser",
			        },
			        "type": "Card",
			      },
			    ],
			    "header": Text {
			      "accessibility": undefined,
			      "endpoint": undefined,
			      "rtl": false,
			      "runs": undefined,
			      "text": "From CGTN",
			    },
			    "type": "CardCollection",
			  },
			  "comments_entry_point_header": undefined,
			  "endscreen": undefined,
			  "game_info": undefined,
			  "heat_map": undefined,
			  "livechat": undefined,
			  "merchandise": undefined,
			  "playability_status": {
			    "audio_only_playability": null,
			    "embeddable": true,
			    "error_screen": null,
			    "reason": "",
			    "status": "OK",
			  },
			  "player_config": {
			    "audio_config": {
			      "enable_per_format_loudness": true,
			      "loudness_db": 2.92,
			      "perceptual_loudness_db": -11.08,
			    },
			    "media_common_config": {
			      "dynamic_readahead_config": {
			        "max_read_ahead_media_time_ms": 120000,
			        "min_read_ahead_media_time_ms": 15000,
			        "read_ahead_growth_rate_ms": 1000,
			      },
			      "media_ustreamer_request_config": {
			        "video_playback_ustreamer_config": "CoQJCt0FCAAlAACAPy0zM3M_NT0Klz9YAWgBchoKFm1mczJfY21mc193ZWJfdjNfMl8wMDMYAHiPTqABAagBALgCANoCmwEQsOoBGIDd2wEgoJwBKKCcATCYdXCIJ4AB9AO4AQHgAQOYAgzAAgHQAgLoAgSAAwKIA4gnqAMDwAMByAMBgAQB0AQB2AQB4AQA-AQHgAV9wAUByAUB4AXQD-gFAfgF0A-ABgGQBgG4BgHQBgHwBgH4BgGAB9APwAcB0AcBgAgBiAgBnQjNzEw-oAjoB-AIAegI____________AfoCtQEtAACgQjUAAKpCZQAAgEBowHCoAdCGA_0BAACAP4UCmpkZP40CAACAP5UC-u1rO7UCAACAP8AC3wPSAhGw__________8BHjxGWlxdXugC6AL9As3MzD2QAwGdAwrXIz2gAwHVAwAAekSYBAHVBAAAIEHoBPAQoAYBtQa9N4Y1vQYzM4NAwAcByAcB5QcAgAlE8AcBgAgBoQgAAAAAAADwv6kIAAAAAAAA8L-wCN8DuAoB-BABggMAkAMBqAMBsAMD0AMB2AMBygQcChMIwKkHEJh1GOgHJQAAAAAoADAAEODUAxjQD9IEDwoICLAJELAJIAEgiCcoAdoEDQoGCPAuEPAuIPAuKAHwBQGYBgGoBoCAAtIGFAjoBxBkGg0IiCcVAAAAPx3NzEw_2AYBiAcBuAcBoAgB0ggGCAEQARgBqQm4HoXrUbiOP7EJuB6F61G4jj_QCQHaCSRTenE5Q3YwcXpsQWVpUE5mSVEzbmZGYW03SUtkcm55S0ZRR1DqCwSLBowGgAwBqAyQAcAMAcgMAdAMAYANAYgNAdgNAeANAYAOAYgOAZgOAYgPAcgPAdAPAegQAYARAZARAbIRFENBTVNDaFVQdUxiSkRQMEVzUVk96BEB4BIB8BIB-BIBuBMBwBMB8BMBmRQAAAAAAADwv7AUAcoUAIinocoLARgBMgwIiQEQzbShhI35jwMyDAj4ARDnk-qGjfmPAzIMCIgBEKvGxYON-Y8DMgwI9wEQgazRho35jwMyDAiHARC41b2DjfmPAzIMCPQBEPii1oaN-Y8DMgwIhgEQ3dmtg435jwMyDAjzARDnhL2GjfmPAzIMCIUBEOeJooON-Y8DMgwI8gEQ2a66ho35jwMyDAigARCH1-CDjfmPAzIMCJYCEOqEwYaN-Y8DMgwIjAEQ7LLxgo35jwMyHAiMARDN6f6GjfmPAxoOQ2dnS0EyUnlZeElCTVEyDAj5ARChoOGKjfmPAzIcCPkBEIO0s5KN-Y8DGg5DZ2dLQTJSeVl4SUJNUTIMCPoBEPnZ3oqN-Y8DMhwI-gEQ85ikjY35jwMaDkNnZ0tBMlJ5WXhJQk1RMgwI-wEQpZ7fio35jwMyHAj7ARD61oKSjfmPAxoOQ2dnS0EyUnlZeElCTVE6AEgAUioaAmVuKAAyGFVDZ3JOei1hRG1jcjJ1dXRvOF9ETDJqZzgAQABYAGAAeACgAQGwAQW6AQMEBTHCAQgBAgMEBQgwXtABABJMAD8V8bcwRQIhANuDo1HNM1R476mBCJAAnJmbjpTRqqPceS9zyHmrpEb7AiBGpf5d33tki-k36YT9RP_44evG4Bzc2mbc5KjMmltCDRoCZWk=",
			      },
			    },
			    "stream_selection_config": {
			      "max_bitrate": "180680000",
			    },
			  },
			  "player_overlays": undefined,
			  "playlist": undefined,
			  "primary_info": undefined,
			  "related_chip_cloud": undefined,
			  "secondary_info": undefined,
			  "storyboards": PlayerStoryboardSpec {
			    "boards": [
			      {
			        "columns": 10,
			        "interval": 0,
			        "rows": 10,
			        "storyboard_count": 1,
			        "template_url": "https://i.ytimg.com/sb/9qIHqX6rdiw/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjJyt_GBg%3D%3D&sigh=rs%24AOn4CLCkBwav8UKa8c0khNajp681X5MmTg",
			        "thumbnail_count": 100,
			        "thumbnail_height": 27,
			        "thumbnail_width": 48,
			        "type": "vod",
			      },
			      {
			        "columns": 10,
			        "interval": 1000,
			        "rows": 10,
			        "storyboard_count": 1,
			        "template_url": "https://i.ytimg.com/sb/9qIHqX6rdiw/storyboard3_L1/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjJyt_GBg%3D%3D&sigh=rs%24AOn4CLB0mHqt2ZaCpaWMCRLCsBcBTwqIrQ",
			        "thumbnail_count": 80,
			        "thumbnail_height": 45,
			        "thumbnail_width": 80,
			        "type": "vod",
			      },
			      {
			        "columns": 5,
			        "interval": 1000,
			        "rows": 5,
			        "storyboard_count": 4,
			        "template_url": "https://i.ytimg.com/sb/9qIHqX6rdiw/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjJyt_GBg%3D%3D&sigh=rs%24AOn4CLAZCSqwWVXhbyONKP3pje9gFgssGw",
			        "thumbnail_count": 80,
			        "thumbnail_height": 90,
			        "thumbnail_width": 160,
			        "type": "vod",
			      },
			      {
			        "columns": 3,
			        "interval": 1000,
			        "rows": 3,
			        "storyboard_count": 9,
			        "template_url": "https://i.ytimg.com/sb/9qIHqX6rdiw/storyboard3_L3/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjJyt_GBg%3D%3D&sigh=rs%24AOn4CLA0sFz1lpdLaSJCdv9h4CtdWQuOpw",
			        "thumbnail_count": 80,
			        "thumbnail_height": 180,
			        "thumbnail_width": 320,
			        "type": "vod",
			      },
			    ],
			    "type": "PlayerStoryboardSpec",
			  },
			  "streaming_data": {
			    "adaptive_formats": [
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 2273860,
			        "bitrate": 3438753,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 22329315,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 1080,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 941,
			          "start": 742,
			        },
			        "init_range": {
			          "end": 741,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 137,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:44.869Z,
			        "last_modified_ms": "1758981584869965",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.640028"",
			        "projection_type": "RECTANGULAR",
			        "quality": "hd1080",
			        "quality_label": "1080p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 1920,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 1699812,
			        "bitrate": 2978558,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 16692156,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 1080,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 449,
			          "start": 220,
			        },
			        "init_range": {
			          "end": 219,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 248,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:50.256Z,
			        "last_modified_ms": "1758981590256103",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "hd1080",
			        "quality_label": "1080p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 1920,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 1233131,
			        "bitrate": 2071426,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 12109353,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 720,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 939,
			          "start": 740,
			        },
			        "init_range": {
			          "end": 739,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 136,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:43.364Z,
			        "last_modified_ms": "1758981583364907",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.64001f"",
			        "projection_type": "RECTANGULAR",
			        "quality": "hd720",
			        "quality_label": "720p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 1280,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 923306,
			        "bitrate": 1378018,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 9066867,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 720,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 449,
			          "start": 220,
			        },
			        "init_range": {
			          "end": 219,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 247,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:49.849Z,
			        "last_modified_ms": "1758981589849601",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "hd720",
			        "quality_label": "720p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 1280,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 652716,
			        "bitrate": 1145869,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 6409678,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 480,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 940,
			          "start": 741,
			        },
			        "init_range": {
			          "end": 740,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 135,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:43.235Z,
			        "last_modified_ms": "1758981583235768",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.4d401e"",
			        "projection_type": "RECTANGULAR",
			        "quality": "large",
			        "quality_label": "480p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 854,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 492807,
			        "bitrate": 753065,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 4839373,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 480,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 449,
			          "start": 220,
			        },
			        "init_range": {
			          "end": 219,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 244,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:49.930Z,
			        "last_modified_ms": "1758981589930360",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "large",
			        "quality_label": "480p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 854,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 312107,
			        "bitrate": 590324,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 3064891,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 360,
			        "high_replication": true,
			        "index_range": {
			          "end": 940,
			          "start": 741,
			        },
			        "init_range": {
			          "end": 740,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 134,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:42.974Z,
			        "last_modified_ms": "1758981582974173",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.4d401e"",
			        "projection_type": "RECTANGULAR",
			        "quality": "medium",
			        "quality_label": "360p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 640,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 295774,
			        "bitrate": 489572,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 2904510,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 360,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 448,
			          "start": 220,
			        },
			        "init_range": {
			          "end": 219,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 243,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:49.516Z,
			        "last_modified_ms": "1758981589516903",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "medium",
			        "quality_label": "360p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 640,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 169653,
			        "bitrate": 264607,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 1666000,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 240,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 939,
			          "start": 740,
			        },
			        "init_range": {
			          "end": 739,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 133,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:42.783Z,
			        "last_modified_ms": "1758981582783719",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.4d4015"",
			        "projection_type": "RECTANGULAR",
			        "quality": "small",
			        "quality_label": "240p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 426,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 160057,
			        "bitrate": 288674,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 1571764,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 240,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 446,
			          "start": 218,
			        },
			        "init_range": {
			          "end": 217,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 242,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:49.473Z,
			        "last_modified_ms": "1758981589473113",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "small",
			        "quality_label": "240p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 426,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 80594,
			        "bitrate": 122488,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 791436,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 144,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 938,
			          "start": 739,
			        },
			        "init_range": {
			          "end": 738,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 160,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:43.809Z,
			        "last_modified_ms": "1758981583809415",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.4d400c"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": "144p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 256,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78560,
			        "audio_channels": undefined,
			        "audio_quality": undefined,
			        "audio_sample_rate": undefined,
			        "audio_track": undefined,
			        "average_bitrate": 92825,
			        "bitrate": 119361,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": {
			          "matrix_coefficients": "BT709",
			          "primaries": "BT709",
			          "transfer_characteristics": "BT709",
			        },
			        "content_length": 911548,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": false,
			        "has_text": false,
			        "has_video": true,
			        "height": 144,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 446,
			          "start": 218,
			        },
			        "init_range": {
			          "end": 217,
			          "start": 0,
			        },
			        "is_auto_dubbed": undefined,
			        "is_descriptive": undefined,
			        "is_drc": undefined,
			        "is_dubbed": undefined,
			        "is_original": undefined,
			        "is_secondary": undefined,
			        "is_type_otf": false,
			        "itag": 278,
			        "language": undefined,
			        "last_modified": 2025-09-27T13:59:49.582Z,
			        "last_modified_ms": "1758981589582442",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/webm; codecs="vp9"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": "144p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": 256,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78622,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_MEDIUM",
			        "audio_sample_rate": 44100,
			        "audio_track": undefined,
			        "average_bitrate": 129550,
			        "bitrate": 130370,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 1273191,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": true,
			        "index_range": {
			          "end": 850,
			          "start": 723,
			        },
			        "init_range": {
			          "end": 722,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": false,
			        "is_dubbed": false,
			        "is_original": true,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 140,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:41.986Z,
			        "last_modified_ms": "1758981581986156",
			        "loudness_db": 2.92,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/mp4; codecs="mp4a.40.2"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78622,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_MEDIUM",
			        "audio_sample_rate": 44100,
			        "audio_track": undefined,
			        "average_bitrate": 129550,
			        "bitrate": 130365,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 1273191,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": true,
			        "index_range": {
			          "end": 850,
			          "start": 723,
			        },
			        "init_range": {
			          "end": 722,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": true,
			        "is_dubbed": false,
			        "is_original": false,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 140,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:50.594Z,
			        "last_modified_ms": "1758981590594765",
			        "loudness_db": -0.75,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/mp4; codecs="mp4a.40.2"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": "CggKA2RyYxIBMQ",
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_LOW",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 43099,
			        "bitrate": 52042,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 423348,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 396,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": false,
			        "is_dubbed": false,
			        "is_original": true,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 249,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:58.498Z,
			        "last_modified_ms": "1758981598498849",
			        "loudness_db": 2.92,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_LOW",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 43436,
			        "bitrate": 51496,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 426657,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 396,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": true,
			        "is_dubbed": false,
			        "is_original": false,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 249,
			        "language": null,
			        "last_modified": 2025-09-27T14:00:14.524Z,
			        "last_modified_ms": "1758981614524931",
			        "loudness_db": -0.75,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": "CggKA2RyYxIBMQ",
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_LOW",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 56368,
			        "bitrate": 65804,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 553684,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 398,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": false,
			        "is_dubbed": false,
			        "is_original": true,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 250,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:58.457Z,
			        "last_modified_ms": "1758981598457081",
			        "loudness_db": 2.92,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_LOW",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 56880,
			        "bitrate": 66176,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 558714,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 398,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": true,
			        "is_dubbed": false,
			        "is_original": false,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 250,
			        "language": null,
			        "last_modified": 2025-09-27T14:00:03.789Z,
			        "last_modified_ms": "1758981603789939",
			        "loudness_db": -0.75,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": "CggKA2RyYxIBMQ",
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_MEDIUM",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 110091,
			        "bitrate": 128082,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 1081386,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 398,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": false,
			        "is_dubbed": false,
			        "is_original": true,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 251,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:58.465Z,
			        "last_modified_ms": "1758981598465829",
			        "loudness_db": 2.92,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": undefined,
			      },
			      Format {
			        "approx_duration_ms": 78581,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_MEDIUM",
			        "audio_sample_rate": 48000,
			        "audio_track": undefined,
			        "average_bitrate": 110819,
			        "bitrate": 128280,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 1088537,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": undefined,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": false,
			        "height": undefined,
			        "high_replication": undefined,
			        "index_range": {
			          "end": 398,
			          "start": 266,
			        },
			        "init_range": {
			          "end": 265,
			          "start": 0,
			        },
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": true,
			        "is_dubbed": false,
			        "is_original": false,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 251,
			        "language": null,
			        "last_modified": 2025-09-27T14:00:13.726Z,
			        "last_modified_ms": "1758981613726586",
			        "loudness_db": -0.75,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "audio/webm; codecs="opus"",
			        "projection_type": "RECTANGULAR",
			        "quality": "tiny",
			        "quality_label": undefined,
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": undefined,
			        "width": undefined,
			        "xtags": "CggKA2RyYxIBMQ",
			      },
			    ],
			    "dash_manifest_url": undefined,
			    "expires": 2025-10-06T00:36:10.540Z,
			    "formats": [
			      Format {
			        "approx_duration_ms": 78622,
			        "audio_channels": 2,
			        "audio_quality": "AUDIO_QUALITY_LOW",
			        "audio_sample_rate": 44100,
			        "audio_track": undefined,
			        "average_bitrate": 405924,
			        "bitrate": 406244,
			        "caption_track": undefined,
			        "cipher": undefined,
			        "color_info": undefined,
			        "content_length": 3989322,
			        "distinct_params": undefined,
			        "drm_families": undefined,
			        "drm_track_type": undefined,
			        "fair_play_key_uri": undefined,
			        "fps": 25,
			        "has_audio": true,
			        "has_text": false,
			        "has_video": true,
			        "height": 360,
			        "high_replication": undefined,
			        "index_range": undefined,
			        "init_range": undefined,
			        "is_auto_dubbed": false,
			        "is_descriptive": false,
			        "is_drc": false,
			        "is_dubbed": false,
			        "is_original": true,
			        "is_secondary": false,
			        "is_type_otf": false,
			        "itag": 18,
			        "language": null,
			        "last_modified": 2025-09-27T13:59:44.103Z,
			        "last_modified_ms": "1758981584103343",
			        "loudness_db": undefined,
			        "max_dvr_duration_sec": undefined,
			        "mime_type": "video/mp4; codecs="avc1.42001E, mp4a.40.2"",
			        "projection_type": "RECTANGULAR",
			        "quality": "medium",
			        "quality_label": "360p",
			        "signature_cipher": undefined,
			        "spatial_audio_type": undefined,
			        "stereo_layout": undefined,
			        "target_duration_dec": undefined,
			        "track_absolute_loudness_lkfs": undefined,
			        "url": "https://rr3---sn-npoeene6.googlevideo.com/videoplayback?expire=1759711030&ei=1rriaLvTJNar9fwPja7sqAQ&ip=103.142.140.232&id=o-AJZb5TnKLmdO01cI_uFOTnIGJ_pR4taOEaxB-nn_EmHj&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1759689430%2C&mh=aZ&mm=31%2C26&mn=sn-npoeene6%2Csn-oguelnsy&ms=au%2Conr&mv=m&mvi=3&pl=24&rms=au%2Cau&initcwndbps=22585000&bui=ATw7iSW9Jiwzyv15tMGvUM2h4Qd_tnMqmaQmdI27p_92DPdgCAseK1B3vydxxqI065NWYnCbwqzF0SWQ&spc=hcYD5Y86kI1v_L9hCnQ1rXpz3tnoT-eiS5-NnukWl0FGUdSN7ira4wtdRDE8h_qs_eVD8RvOYeaZuw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=9EY3OZKNDeJ72TLwH0A4TvIQ&rqh=1&gir=yes&clen=3989322&ratebypass=yes&dur=78.622&lmt=1758981584103343&mt=1759689024&fvip=3&fexp=51355912%2C51552689%2C51565116%2C51565681%2C51580968&c=WEB&sefc=1&txp=5319224&n=1otyV7RA6qF7Cs6y&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAPbJfDcKSyv1VpUiMhFkIMqFX1NnxKeZqtSa2rjtfrL6AiEArqw8lylqzmga49STE0ItKuG20zYmhm_DynOpGh7Ri6c%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgMbI-O6zAqs3kiaCBxM1rvnDXuZfE4Ze4t868L-pBWgQCIQD3Qcyp5vzCIsAGKBQBWBzkL2ZoV8sSpsrbtCAcWsYW0Q%3D%3D",
			        "width": 640,
			        "xtags": undefined,
			      },
			    ],
			    "hls_manifest_url": undefined,
			    "server_abr_streaming_url": "https://rr3---sn-npoeene6.googlevideo.com/videoplayback?expire=1759711030&ei=1rriaLvTJNar9fwPja7sqAQ&ip=103.142.140.232&id=o-AJZb5TnKLmdO01cI_uFOTnIGJ_pR4taOEaxB-nn_EmHj&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1759689430%2C&mh=aZ&mm=31%2C26&mn=sn-npoeene6%2Csn-oguelnsy&ms=au%2Conr&mv=m&mvi=3&pl=24&rms=au%2Cau&initcwndbps=22585000&spc=hcYD5Y85kI1v_L9hCnQ1rXpz3tnpT-eiS5-NnukWl0FGUdSN7ira4wtdRDE8vfrU-_dAkRsmYX4&svpuc=1&ns=2fRBNNtObYf-DxAbGMNyAokQ&sabr=1&rqh=1&mt=1759689024&fvip=3&keepalive=yes&fexp=51355912%2C51552689%2C51565116%2C51565681%2C51580968&c=WEB&n=vbIMeGMzJuNUlhFg&sparams=expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Cspc%2Csvpuc%2Cns%2Csabr%2Crqh&sig=AJfQdSswRQIgKnNiplA1vQwpcgRQgK-BQapyzWD1wQuFxXR2bHzuxxECIQCqy5nuty9hAMQJyiCkhlo-OoCU9sUErsNUnQPw9owZcg%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgMbI-O6zAqs3kiaCBxM1rvnDXuZfE4Ze4t868L-pBWgQCIQD3Qcyp5vzCIsAGKBQBWBzkL2ZoV8sSpsrbtCAcWsYW0Q%3D%3D",
			  },
			  "watch_next_feed": undefined,
			}
		`)
	}, 60000)
})
