/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProxyRouteImport } from './routes/proxy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PointsRouteImport } from './routes/points'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MediaDownloadRouteImport } from './routes/media.download'
import { Route as MediaIdRouteImport } from './routes/media.$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as ApiOpenapiRouteImport } from './routes/api.openapi'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPointsPricingRouteImport } from './routes/admin.points-pricing'
import { Route as AdminAiProvidersRouteImport } from './routes/admin.ai-providers'
import { Route as AdminAiModelsRouteImport } from './routes/admin.ai-models'
import { Route as MediaIdIndexRouteImport } from './routes/media.$id.index'
import { Route as MediaIdSubtitlesRouteImport } from './routes/media.$id.subtitles'
import { Route as MediaIdCommentsRouteImport } from './routes/media.$id.comments'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiRenderCfCallbackRouteImport } from './routes/api.render.cf-callback'
import { Route as ApiOrpcSplatRouteImport } from './routes/api.orpc.$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiMediaIdSubtitlesRouteImport } from './routes/api.media.$id.subtitles'
import { Route as ApiMediaIdSourceRouteImport } from './routes/api.media.$id.source'
import { Route as ApiMediaIdRenderedInfoRouteImport } from './routes/api.media.$id.rendered-info'
import { Route as ApiMediaIdRenderedRouteImport } from './routes/api.media.$id.rendered'
import { Route as ApiMediaIdDownloadedRouteImport } from './routes/api.media.$id.downloaded'
import { Route as ApiMediaIdCommentsDataRouteImport } from './routes/api.media.$id.comments-data'
import { Route as ApiInternalAiAsrProviderRouteImport } from './routes/api.internal.ai.asr-provider'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MediaDownloadRoute = MediaDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => MediaRoute,
} as any)
const MediaIdRoute = MediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MediaRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPointsPricingRoute = AdminPointsPricingRouteImport.update({
  id: '/points-pricing',
  path: '/points-pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiProvidersRoute = AdminAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AdminRoute,
} as any)
const MediaIdIndexRoute = MediaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaIdRoute,
} as any)
const MediaIdSubtitlesRoute = MediaIdSubtitlesRouteImport.update({
  id: '/subtitles',
  path: '/subtitles',
  getParentRoute: () => MediaIdRoute,
} as any)
const MediaIdCommentsRoute = MediaIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => MediaIdRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderCfCallbackRoute = ApiRenderCfCallbackRouteImport.update({
  id: '/api/render/cf-callback',
  path: '/api/render/cf-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrpcSplatRoute = ApiOrpcSplatRouteImport.update({
  id: '/api/orpc/$',
  path: '/api/orpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdSubtitlesRoute = ApiMediaIdSubtitlesRouteImport.update({
  id: '/api/media/$id/subtitles',
  path: '/api/media/$id/subtitles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdSourceRoute = ApiMediaIdSourceRouteImport.update({
  id: '/api/media/$id/source',
  path: '/api/media/$id/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRenderedInfoRoute = ApiMediaIdRenderedInfoRouteImport.update({
  id: '/api/media/$id/rendered-info',
  path: '/api/media/$id/rendered-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRenderedRoute = ApiMediaIdRenderedRouteImport.update({
  id: '/api/media/$id/rendered',
  path: '/api/media/$id/rendered',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdDownloadedRoute = ApiMediaIdDownloadedRouteImport.update({
  id: '/api/media/$id/downloaded',
  path: '/api/media/$id/downloaded',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdCommentsDataRoute = ApiMediaIdCommentsDataRouteImport.update({
  id: '/api/media/$id/comments-data',
  path: '/api/media/$id/comments-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAiAsrProviderRoute =
  ApiInternalAiAsrProviderRouteImport.update({
    id: '/api/internal/ai/asr-provider',
    path: '/api/internal/ai/asr-provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/channels': typeof ChannelsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/proxy': typeof ProxyRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/points-pricing': typeof AdminPointsPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/media/$id': typeof MediaIdRouteWithChildren
  '/media/download': typeof MediaDownloadRoute
  '/admin/': typeof AdminIndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/render/cf-callback': typeof ApiRenderCfCallbackRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/media/$id/comments': typeof MediaIdCommentsRoute
  '/media/$id/subtitles': typeof MediaIdSubtitlesRoute
  '/media/$id/': typeof MediaIdIndexRoute
  '/api/internal/ai/asr-provider': typeof ApiInternalAiAsrProviderRoute
  '/api/media/$id/comments-data': typeof ApiMediaIdCommentsDataRoute
  '/api/media/$id/downloaded': typeof ApiMediaIdDownloadedRoute
  '/api/media/$id/rendered': typeof ApiMediaIdRenderedRoute
  '/api/media/$id/rendered-info': typeof ApiMediaIdRenderedInfoRoute
  '/api/media/$id/source': typeof ApiMediaIdSourceRoute
  '/api/media/$id/subtitles': typeof ApiMediaIdSubtitlesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/login': typeof LoginRoute
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/proxy': typeof ProxyRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/points-pricing': typeof AdminPointsPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/media/download': typeof MediaDownloadRoute
  '/admin': typeof AdminIndexRoute
  '/media': typeof MediaIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/render/cf-callback': typeof ApiRenderCfCallbackRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/media/$id/comments': typeof MediaIdCommentsRoute
  '/media/$id/subtitles': typeof MediaIdSubtitlesRoute
  '/media/$id': typeof MediaIdIndexRoute
  '/api/internal/ai/asr-provider': typeof ApiInternalAiAsrProviderRoute
  '/api/media/$id/comments-data': typeof ApiMediaIdCommentsDataRoute
  '/api/media/$id/downloaded': typeof ApiMediaIdDownloadedRoute
  '/api/media/$id/rendered': typeof ApiMediaIdRenderedRoute
  '/api/media/$id/rendered-info': typeof ApiMediaIdRenderedInfoRoute
  '/api/media/$id/source': typeof ApiMediaIdSourceRoute
  '/api/media/$id/subtitles': typeof ApiMediaIdSubtitlesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/channels': typeof ChannelsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/points': typeof PointsRoute
  '/privacy': typeof PrivacyRoute
  '/proxy': typeof ProxyRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/points-pricing': typeof AdminPointsPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/media/$id': typeof MediaIdRouteWithChildren
  '/media/download': typeof MediaDownloadRoute
  '/admin/': typeof AdminIndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/orpc/$': typeof ApiOrpcSplatRoute
  '/api/render/cf-callback': typeof ApiRenderCfCallbackRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/media/$id/comments': typeof MediaIdCommentsRoute
  '/media/$id/subtitles': typeof MediaIdSubtitlesRoute
  '/media/$id/': typeof MediaIdIndexRoute
  '/api/internal/ai/asr-provider': typeof ApiInternalAiAsrProviderRoute
  '/api/media/$id/comments-data': typeof ApiMediaIdCommentsDataRoute
  '/api/media/$id/downloaded': typeof ApiMediaIdDownloadedRoute
  '/api/media/$id/rendered': typeof ApiMediaIdRenderedRoute
  '/api/media/$id/rendered-info': typeof ApiMediaIdRenderedInfoRoute
  '/api/media/$id/source': typeof ApiMediaIdSourceRoute
  '/api/media/$id/subtitles': typeof ApiMediaIdSubtitlesRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/channels'
    | '/login'
    | '/media'
    | '/points'
    | '/privacy'
    | '/proxy'
    | '/tasks'
    | '/admin/ai-models'
    | '/admin/ai-providers'
    | '/admin/points-pricing'
    | '/admin/users'
    | '/api/openapi'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/media/$id'
    | '/media/download'
    | '/admin/'
    | '/media/'
    | '/api/orpc/$'
    | '/api/render/cf-callback'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/media/$id/comments'
    | '/media/$id/subtitles'
    | '/media/$id/'
    | '/api/internal/ai/asr-provider'
    | '/api/media/$id/comments-data'
    | '/api/media/$id/downloaded'
    | '/api/media/$id/rendered'
    | '/api/media/$id/rendered-info'
    | '/api/media/$id/source'
    | '/api/media/$id/subtitles'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/login'
    | '/points'
    | '/privacy'
    | '/proxy'
    | '/tasks'
    | '/admin/ai-models'
    | '/admin/ai-providers'
    | '/admin/points-pricing'
    | '/admin/users'
    | '/api/openapi'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/media/download'
    | '/admin'
    | '/media'
    | '/api/orpc/$'
    | '/api/render/cf-callback'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/media/$id/comments'
    | '/media/$id/subtitles'
    | '/media/$id'
    | '/api/internal/ai/asr-provider'
    | '/api/media/$id/comments-data'
    | '/api/media/$id/downloaded'
    | '/api/media/$id/rendered'
    | '/api/media/$id/rendered-info'
    | '/api/media/$id/source'
    | '/api/media/$id/subtitles'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/channels'
    | '/login'
    | '/media'
    | '/points'
    | '/privacy'
    | '/proxy'
    | '/tasks'
    | '/admin/ai-models'
    | '/admin/ai-providers'
    | '/admin/points-pricing'
    | '/admin/users'
    | '/api/openapi'
    | '/demo/orpc-todo'
    | '/demo/tanstack-query'
    | '/media/$id'
    | '/media/download'
    | '/admin/'
    | '/media/'
    | '/api/orpc/$'
    | '/api/render/cf-callback'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/media/$id/comments'
    | '/media/$id/subtitles'
    | '/media/$id/'
    | '/api/internal/ai/asr-provider'
    | '/api/media/$id/comments-data'
    | '/api/media/$id/downloaded'
    | '/api/media/$id/rendered'
    | '/api/media/$id/rendered-info'
    | '/api/media/$id/source'
    | '/api/media/$id/subtitles'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChannelsRoute: typeof ChannelsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRouteWithChildren
  PointsRoute: typeof PointsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProxyRoute: typeof ProxyRoute
  TasksRoute: typeof TasksRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiOrpcSplatRoute: typeof ApiOrpcSplatRoute
  ApiRenderCfCallbackRoute: typeof ApiRenderCfCallbackRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiInternalAiAsrProviderRoute: typeof ApiInternalAiAsrProviderRoute
  ApiMediaIdCommentsDataRoute: typeof ApiMediaIdCommentsDataRoute
  ApiMediaIdDownloadedRoute: typeof ApiMediaIdDownloadedRoute
  ApiMediaIdRenderedRoute: typeof ApiMediaIdRenderedRoute
  ApiMediaIdRenderedInfoRoute: typeof ApiMediaIdRenderedInfoRoute
  ApiMediaIdSourceRoute: typeof ApiMediaIdSourceRoute
  ApiMediaIdSubtitlesRoute: typeof ApiMediaIdSubtitlesRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/media/download': {
      id: '/media/download'
      path: '/download'
      fullPath: '/media/download'
      preLoaderRoute: typeof MediaDownloadRouteImport
      parentRoute: typeof MediaRoute
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteImport
      parentRoute: typeof MediaRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/points-pricing': {
      id: '/admin/points-pricing'
      path: '/points-pricing'
      fullPath: '/admin/points-pricing'
      preLoaderRoute: typeof AdminPointsPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-providers': {
      id: '/admin/ai-providers'
      path: '/ai-providers'
      fullPath: '/admin/ai-providers'
      preLoaderRoute: typeof AdminAiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/media/$id/': {
      id: '/media/$id/'
      path: '/'
      fullPath: '/media/$id/'
      preLoaderRoute: typeof MediaIdIndexRouteImport
      parentRoute: typeof MediaIdRoute
    }
    '/media/$id/subtitles': {
      id: '/media/$id/subtitles'
      path: '/subtitles'
      fullPath: '/media/$id/subtitles'
      preLoaderRoute: typeof MediaIdSubtitlesRouteImport
      parentRoute: typeof MediaIdRoute
    }
    '/media/$id/comments': {
      id: '/media/$id/comments'
      path: '/comments'
      fullPath: '/media/$id/comments'
      preLoaderRoute: typeof MediaIdCommentsRouteImport
      parentRoute: typeof MediaIdRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render/cf-callback': {
      id: '/api/render/cf-callback'
      path: '/api/render/cf-callback'
      fullPath: '/api/render/cf-callback'
      preLoaderRoute: typeof ApiRenderCfCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orpc/$': {
      id: '/api/orpc/$'
      path: '/api/orpc/$'
      fullPath: '/api/orpc/$'
      preLoaderRoute: typeof ApiOrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/subtitles': {
      id: '/api/media/$id/subtitles'
      path: '/api/media/$id/subtitles'
      fullPath: '/api/media/$id/subtitles'
      preLoaderRoute: typeof ApiMediaIdSubtitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/source': {
      id: '/api/media/$id/source'
      path: '/api/media/$id/source'
      fullPath: '/api/media/$id/source'
      preLoaderRoute: typeof ApiMediaIdSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/rendered-info': {
      id: '/api/media/$id/rendered-info'
      path: '/api/media/$id/rendered-info'
      fullPath: '/api/media/$id/rendered-info'
      preLoaderRoute: typeof ApiMediaIdRenderedInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/rendered': {
      id: '/api/media/$id/rendered'
      path: '/api/media/$id/rendered'
      fullPath: '/api/media/$id/rendered'
      preLoaderRoute: typeof ApiMediaIdRenderedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/downloaded': {
      id: '/api/media/$id/downloaded'
      path: '/api/media/$id/downloaded'
      fullPath: '/api/media/$id/downloaded'
      preLoaderRoute: typeof ApiMediaIdDownloadedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/comments-data': {
      id: '/api/media/$id/comments-data'
      path: '/api/media/$id/comments-data'
      fullPath: '/api/media/$id/comments-data'
      preLoaderRoute: typeof ApiMediaIdCommentsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/ai/asr-provider': {
      id: '/api/internal/ai/asr-provider'
      path: '/api/internal/ai/asr-provider'
      fullPath: '/api/internal/ai/asr-provider'
      preLoaderRoute: typeof ApiInternalAiAsrProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAiProvidersRoute: typeof AdminAiProvidersRoute
  AdminPointsPricingRoute: typeof AdminPointsPricingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAiProvidersRoute: AdminAiProvidersRoute,
  AdminPointsPricingRoute: AdminPointsPricingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MediaIdRouteChildren {
  MediaIdCommentsRoute: typeof MediaIdCommentsRoute
  MediaIdSubtitlesRoute: typeof MediaIdSubtitlesRoute
  MediaIdIndexRoute: typeof MediaIdIndexRoute
}

const MediaIdRouteChildren: MediaIdRouteChildren = {
  MediaIdCommentsRoute: MediaIdCommentsRoute,
  MediaIdSubtitlesRoute: MediaIdSubtitlesRoute,
  MediaIdIndexRoute: MediaIdIndexRoute,
}

const MediaIdRouteWithChildren =
  MediaIdRoute._addFileChildren(MediaIdRouteChildren)

interface MediaRouteChildren {
  MediaIdRoute: typeof MediaIdRouteWithChildren
  MediaDownloadRoute: typeof MediaDownloadRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaIdRoute: MediaIdRouteWithChildren,
  MediaDownloadRoute: MediaDownloadRoute,
  MediaIndexRoute: MediaIndexRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChannelsRoute: ChannelsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRouteWithChildren,
  PointsRoute: PointsRoute,
  PrivacyRoute: PrivacyRoute,
  ProxyRoute: ProxyRoute,
  TasksRoute: TasksRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiOrpcSplatRoute: ApiOrpcSplatRoute,
  ApiRenderCfCallbackRoute: ApiRenderCfCallbackRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiInternalAiAsrProviderRoute: ApiInternalAiAsrProviderRoute,
  ApiMediaIdCommentsDataRoute: ApiMediaIdCommentsDataRoute,
  ApiMediaIdDownloadedRoute: ApiMediaIdDownloadedRoute,
  ApiMediaIdRenderedRoute: ApiMediaIdRenderedRoute,
  ApiMediaIdRenderedInfoRoute: ApiMediaIdRenderedInfoRoute,
  ApiMediaIdSourceRoute: ApiMediaIdSourceRoute,
  ApiMediaIdSubtitlesRoute: ApiMediaIdSubtitlesRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
