name = "media-orchestrator"
main = "index.ts"
compatibility_date = "2024-05-01"

workers_dev = true

[[kv_namespaces]]
binding = "JOBS"
id = "local-jobs-namespace"
preview_id = "local-jobs-namespace"

[[r2_buckets]]
binding = "RENDER_BUCKET"
bucket_name = "vidgen-render"

[vars]
JOB_TTL_SECONDS = 86400
CONTAINER_BASE_URL = "http://localhost:8080"
NEXT_BASE_URL = "http://localhost:3000"
JOB_CALLBACK_HMAC_SECRET = "replace-with-strong-secret"

# S3-compatible storage for both prod (R2 S3 endpoint) and dev (MinIO)
# For production with R2, set:
#   S3_ENDPOINT = "https://<accountid>.r2.cloudflarestorage.com"
#   S3_STYLE = "vhost"  # virtual host style
# For dev with MinIO, set:
#   S3_ENDPOINT = "http://minio:9000"  (in docker network) or http://127.0.0.1:9000
#   S3_STYLE = "path"   # path style
S3_ENDPOINT = ""
S3_ACCESS_KEY_ID = ""
S3_SECRET_ACCESS_KEY = ""
S3_BUCKET_NAME = "vidgen-render"
S3_STYLE = "vhost"
S3_REGION = "auto"
